# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e22540372940fdbb487d6549f8910b7d55c6e0e0278ef11a5fa6a58ccad74fd216558a31dd5d04162788de121e40ca998b81ac4424dd2e7ae06b1166ce78f211

test:
  secret_key_base: db5658e3dfc66415204bb40f3109b017c7a65434e1856706e968c55715e241287e93577c682bc5b661f9a7698817e9452f65898ec4885399fad6f91e1c277ca3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
